# Generated by Django 4.0.6 on 2022-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDeBodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columnas', models.IntegerField(verbose_name='Columnas')),
                ('filas', models.IntegerField(verbose_name='Filas')),
                ('bloque', models.CharField(max_length=200, verbose_name='Bloque')),
                ('ContenidosInv', models.CharField(default='N/A', max_length=200, verbose_name='cont')),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
