# Generated by Django 4.0.6 on 2022-08-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columnas', models.IntegerField()),
                ('filas', models.IntegerField()),
                ('bloque', models.CharField(max_length=200)),
            ],
        ),
    ]
