# Generated by Django 4.0.6 on 2022-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDeBodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columnas', models.IntegerField()),
                ('filas', models.IntegerField()),
                ('bloque', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
