# Generated by Django 4.0.6 on 2022-11-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('IdTrabajador', models.CharField(max_length=200, verbose_name='IdTrbajador')),
                ('Descripcion', models.CharField(max_length=800, verbose_name='Descripcion')),
                ('Estado', models.BooleanField(verbose_name='Estado')),
            ],
        ),
    ]
