# Generated by Django 4.0.6 on 2022-08-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_inventariodebodega_delete_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodebodega',
            name='bloque',
            field=models.CharField(max_length=200, verbose_name='Bloque'),
        ),
        migrations.AlterField(
            model_name='inventariodebodega',
            name='columnas',
            field=models.IntegerField(verbose_name='Columnas'),
        ),
        migrations.AlterField(
            model_name='inventariodebodega',
            name='filas',
            field=models.IntegerField(verbose_name='Filas'),
        ),
    ]
