# Generated by Django 4.0.6 on 2022-11-15 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_inventariodebodega_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodebodega',
            name='ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
