# Generated by Django 4.0.6 on 2022-08-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_inventariodebodega_columnas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventarioDeBodega',
            new_name='InventarioBodega',
        ),
    ]
