# Generated by Django 4.0.6 on 2022-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_inventariomanejado_delete_inventariodebodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columnas', models.IntegerField(verbose_name='Columnas')),
                ('filas', models.IntegerField(verbose_name='Filas')),
                ('bloque', models.CharField(max_length=200, verbose_name='Bloque')),
            ],
        ),
        migrations.DeleteModel(
            name='inventarioManejado',
        ),
    ]
