# Generated by Django 4.0.6 on 2022-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_inventariobodega_delete_inventariomanejado'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskBodega',
            fields=[
                ('idTask', models.AutoField(primary_key=True, serialize=False, verbose_name='idTask')),
                ('nombreTask', models.CharField(max_length=300, verbose_name='NTask')),
                ('id', models.CharField(max_length=200, verbose_name='Id')),
                ('DescTask', models.CharField(max_length=600, verbose_name='Desc')),
            ],
        ),
        migrations.RenameModel(
            old_name='InventarioBodega',
            new_name='InventarioDeBodega',
        ),
    ]
