# Generated by Django 4.0.6 on 2022-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_taskbodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodebodega',
            name='ContenidosInv',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Cont'),
        ),
        migrations.AddField(
            model_name='taskbodega',
            name='ActiveTask',
            field=models.BooleanField(default=False, verbose_name='ActiveTask'),
        ),
    ]
