# Generated by Django 4.0.6 on 2022-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_inventariodebodega_contenidosinv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodebodega',
            name='ContenidosInv',
            field=models.CharField(default='N/A', max_length=200, verbose_name='cont'),
        ),
    ]
