# Generated by Django 4.0.6 on 2022-09-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_inventariodebodega_contenidosinv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbodega',
            name='idTask',
        ),
        migrations.AddField(
            model_name='taskbodega',
            name='idTrabajador',
            field=models.CharField(default='0', max_length=200, verbose_name='Id_Trabajador'),
        ),
        migrations.AlterField(
            model_name='taskbodega',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
