# Generated by Django 4.0.6 on 2022-09-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_remove_taskbodega_idtask_taskbodega_idtrabajador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareasDelAlmacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTarea', models.CharField(max_length=400, verbose_name='Nombre_Tarea')),
                ('idTrabajador', models.CharField(max_length=200, verbose_name='Id_Worker')),
                ('Descripcion', models.CharField(max_length=800, verbose_name='Descripcion')),
                ('Estado', models.BooleanField(verbose_name='Estado')),
            ],
        ),
        migrations.DeleteModel(
            name='taskBodega',
        ),
    ]
