# Generated by Django 4.0.6 on 2022-09-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_tareasdelalmacen_delete_taskbodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasdelalmacen',
            name='Estado',
        ),
    ]
