# Generated by Django 4.0.6 on 2022-09-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_remove_tareasdelalmacen_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasdelalmacen',
            name='Descripcion',
        ),
    ]
