# Generated by Django 4.0.6 on 2022-09-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_remove_tareasdelalmacen_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TareasDelAlmacen',
        ),
    ]
